tibue99/ezcord

docs/ezcord/bot.rst
src/ezcord/__init__.py
src/ezcord/bot.py
src/ezcord/cogs/help.py
src/ezcord/internal/language/de.json
src/ezcord/internal/language/en.json

This allows an automatic help command

Add custom cog class

---

ezcord/bot.py
ezcord/sql.py

Improve general connection handling and add automatic support for some data types

Add more DB features

---

ezcord/bot.py
ezcord/cogs/status_changer.py

Create `bot.add_status_changer` to automatically change to bot's activity and status in a given interval.

Add status changer

---

docs/ezcord/blacklist.rst
docs/ezcord/modules.rst
ezcord/__init__.py
ezcord/blacklist.py
ezcord/bot.py
ezcord/cogs/blacklist.py
ezcord/errors.py
ezcord/internal/__init__.py
ezcord/internal/config.py
ezcord/internal/language/de.json
ezcord/internal/language/en.json

This PR adds a blacklist to ban users from using the bot.

Add blacklist

---

ezcord/blacklist.py
ezcord/bot.py
ezcord/cogs/blacklist.py
ezcord/internal/config.py

Blacklist commands can now be disabled and customized. This solves #38 and #39.

Improve blacklist

---

ezcord/bot.py
ezcord/internal/embed_templates.py
ezcord/internal/ready_style.py
ezcord/utils.py

- Added `guild_count` and `user_count` as new embed variables
- Added `cmd_count` property for the bot
- Added `utils.count_lines`
This closes #40

Add more variables

---

ezcord/utils.py

- Fixed decoding errors
- Added option to ignore files/folders
- Added option to enable/disable empty line counting
- Added patting matcher for files

Improve line counter

---

ezcord/sql.py

Add `executemany` to execute multiqueries within the `DBHandler`.

Add DBHandler.executemany

---

.github/workflows/checks.yml
.github/workflows/python-publish.yml
pyproject.toml
tests/test_times.py

This PR officially adds Python 3.12 to the list of supported Python versions.

Add support for Python 3.12

---

ezcord/errors.py
ezcord/utils.py

- Added `load_message` function to retrieve a message with the message URL
- Added exception classes

feat: add message utils

---

ezcord/i18n.py

- You can now pass strings as a locale object, if you want to use a specific locale to load text
- Keys can now contain the full language file path, separated by dots

feat: improve i18n

---

ezcord/internal/dc/__init__.py
ezcord/internal/embed_templates.py

Some features don't need a discord library to work properly. This PR allows EzCord usage without an installed Discord Library for certain features.

feat: allow usage without a supported discord library

---

README.md
dev-requirements.txt
docs/index.rst
docs/pages/contributing.rst

- Added contribution guide
- Dev requirements now include all other requirements
- Added new features to `README.md`

docs: add contribution guide

---

ezcord/bot.py
ezcord/internal/dc/__init__.py

Added `ezcord.AutoShardedBot` to combine `discord.AutoShardedBot` with `ezcord.Bot`

feat: add AutoShardedBot

---

ezcord/blacklist.py
ezcord/sql/__init__.py
requirements.txt

- Added `aiocache` requirement to cache blacklisted users
- Removed `asyncpg` as a mandatory requirement, installation is only needed when `PGHandler` is used

feat: add blacklist cache and adjust deps

---

ezcord/internal/dc/__init__.py
ezcord/utils.py
tests/test_utils.py

Add `utils.convert_color` (build on top of the existing `ColorConverter` from Pycord and discord.py)

feat: add color converter

---

docs/examples/dropdown_paginator.rst
docs/examples/examples.rst
examples/.env.example
examples/database/example.env
examples/dropdown_paginator.py
ezcord/components.py
ezcord/internal/dc/__init__.py

Add auto pagination for dropdown menus.

feat: add dropdown paginator

---

ezcord/components.py

This PR adds the option to ignore errors in the view `on_timeout` event.

feat: improve error handling for views

---

.github/workflows/checks.yml
ezcord/internal/language/languages.py
ezcord/internal/translation.py
ezcord/times.py
pyproject.toml
readthedocs.yaml
requirements.txt

chore: support Python 3.13

---

ezcord/cogs/blacklist.py
ezcord/utils.py
requirements.txt

- Change output of `/admin server_show` from `.txt` to `.yaml`
- Add `utils.create_yaml_file`

feat: add utils.create_yaml_file

---

ezcord/i18n.py

This PR adds translation support for new Discord components.
References:
- Pycord: https://github.com/Pycord-Development/pycord/pull/2707
- Discord: https://discord.com/developers/docs/components/reference

feat: components v2

---

ezcord/bot.py

This PR introduces the new helper method `load_extension`, to improve the handling of errors when loading extensions.

feat: add safe extension loading
